### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jakubkoziejj** [PixelsetDev/Saturn#75]
**Describe the bug**
Saturn installation not possible due to an error. ERROR INSERT TABLE USERS. PROFILE_PHOTO, VARCHAR is over the limit.

**Comment by lewmilburn** [comment]
Just looking into this, could also be linked to https://tracker.lmwn.co.uk/issues/?i=S14. I think something in the code doesn't work on localhost environments, as none of these issues are replicable in hosting environments.
